export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const AD_LOADING = 'AD_LOADING';
export const GET_ADS = 'GET_ADS';
export const GET_AD = 'GET_AD';
export const ADD_AD = 'ADD_AD';
export const DELETE_AD = 'DELETE_AD';

export const GET_USER_MAP = 'GET_USER_MAP';
export const GET_USER_TRIPS = 'GET_USER_TRIPS';
export const ADD_FLIGHT = 'ADD_FLIGHT';
export const ADD_TRIP = 'ADD_TRIP';
export const USER_MAP_LOADING = 'USER_MAP_LOADING';
export const SELECT_MAP_ELEMENT = 'SELECT_MAP_ELEMENT';

export const GET_FINANCIAL_STATEMENT = 'GET_FINANCIAL_STATEMENT';
export const FINANCIAL_STATEMENT_LOADING = 'FINANCIAL_STATEMENT_LOADING';

export const GET_LIFE_WHEEL = 'GET_LIFE_WHEEL';
export const LIFE_WHEEL_LOADING = 'LIFE_WHEEL_LOADING';
